url: https://y7kim.github.io
baseurl: 

# Site settings
title: Amati Gattei
email: davidegattei@riminiservizi.com
description: "Dottori Commercialisti con una significativa esperienza nella consulenza fiscale a clienti aziendali e privati ed esperti in diritto commerciale, diritto societario, diritto fallimentare e valutazioni d'azienda. Offriamo consulenza fiscale a società straniere che investono in Italia."


# Team names, titles and social links
people:
- name: Davide Gattei
  pic: 1
  position: Dottore Commercialista
  social:
    - title: linkedin
      url: http://linkedin.com/in/davide-g-a60a0340
    - title: at 
      url: mailto:gatteidavide@riminiservizi.com

- name: Monica Amati
  pic: 2
  position: Dottore Commercialista
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/monica-amati/
    - title: at
      url: mailto:amatimonica@riminiservizi.com

- name: Matteo Lombardini
  pic: 3
  position: Dottore Commercialista
  social:
    - title: linkedin
      url: #
    - title: at
      url: mailto:lombardinimatteo@riminiservizi.com

- name: Laura Semprini
  pic: 4
  position: Contabilita, Fisco, Consulenza
  social:
    - title: linkedin
      url: #
    - title: at
      url: mailto:semprinilaura@riminiservizi.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Via Ariete 18, 3
  - line: Rimini, 47923

# Build settings
markdown: kramdown
permalink: pretty